baseURL: "https://zen-lex.github.io/"

title: JABK.
paginate: 5
theme: ["hugo-redirect", "PaperMod"]
languageCode: fr-fr

enableRobotsTXT: true
enableEmoji: true

minify:
  disableXML: true
  minifyOutput: true

defaultContentLanguage: fr
languages:
  fr:
    languageName: "Français :fr:"
    languageAltName: Français
    weight: 1
    menu:
      main:
        - identifier: projects
          name: Projets
          url: /projects/
          weight: 1
        - identifier: about
          name: A Propos
          url: /about/
          weight: 2

  en:
    languageName: "English :uk:"
    languageAltName: English
    weight: 2
    menu:
      main:
      - identifier: projets
        name: Projects
        url: /projects/
        weight: 1
      - identifier: about
        name: About
        url: /about/
        weight: 2

params:
  #General parameters
  displayfullLangName: true
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  keywords: [Blog, Portfolio, PaperMod]
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: ":date_long"
  defaultTheme: auto # dark, light, auto
  disableThemeToggle: false

  assets:
    # disableHLJS: true # to disable highlight.js
    disableFingerprinting: true
    favicon: "images/favicon.png"
    favicon16x16: "images/favicon.png"
    favicon32x32: "images/favicon.png"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Home"

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    defaultContentLanguage: fr

    title: "Hi there \U0001F44B"
    subtitle: "Welcome to my blog"
    imageUrl: "images/Lumpy.jpg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Projets
        url: projets
      - name: CV
        url: "files/resume.pdf"

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: email
      url: "mailto:jbertink@gmail.com"
    - name: github
      url: "https://github.com/Zen-lex"
    - name: linkedin
      url: "https://linkedin.com/in/jabk"
    - name: instagram
      url: "https://www.instagram.com/julien.bk0/"
    - name: spotify
      url: "https://open.spotify.com/user/qghl2te58xxxlj4xrr94gh5g6?si=1426d692e10e4b9f"

  cover:
    relative: false # when using page bundles set this to true
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page

  editPost:
    disabled: true
    URL: "https://github.com/Zen-lex/"
    Text: "Source Code" # edit text
    appendFilePath: false # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

buildDrafts: true
buildFuture: false
buildExpired: false